### PR TITLE
Feature/widget date generic

### PR DESCRIPTION
**Pull request by techgardeners**
Added a new "date generic" widget that allows you to view dates in a "human" format.
It was born from my personal need to have a prettier view of a signal with ISO 8601 format.
I added the ability to customize output formatting by adding a parameter in the configuration widget (dateFormat).
If I made a mistake or didn't understand something, feel free to tell me.
I'm sorry if in a couple of files an automatic style fixes ended up in the commit

### CODE REVIEW

**Comment by techgardeners** [comment]
Added timezone config

**Comment by godind** [comment]
Hi. Thanks for the widget! I was curious about the use case for this widget ? What do you use it for?

**Comment by techgardeners** [comment]
For turn this

image

into this

image

but you can set the format as you like

image

image

**Comment by techgardeners** [comment]
I know it could be done on the server side (signalk) but I think it's more correct to have the "raw" data available and then on the frontend side (dashboard) to view it as you prefer.

**Comment by techgardeners** [comment]
image

**Comment by godind** [comment]
Makes complete sense when using different time zones! Great use case. I'll merge it. We need to push a big PR first. One that will enable automatic config sharing to all devices if you use user login (removing the annoying need to recreate you config per device or having to save and copy manually). But it needs sk to publish its next version first because we found a bug and we can't fully test until then.

On another note, I was think of building a widget framework to facilitate extensions. Something like ng create kip-widget. It would make a widget skeleton with config, required services and path subscription template. Would that help contributors or you think it's not something really valuable?

**Comment by techgardeners** [comment]
yes, that would be a great feature.

**Comment by godind** [comment]
Just fixed a widget title refresh issue. Thanks for the widget!

**Pull request merged**
