### PR TITLE
Added basic pwa webapp

### LINKED ISSUE #21: Allow offline use via PWA
https://medium.com/@nsmirnova/creating-pwa-with-angular-5-part-2-progressifying-the-application-449e3a706129

:)

### PR DESCRIPTION
**Pull request by VibroAxe**
I can see mxtommy made a start on a pwa, however the addition of a service worker seems unnecessary (and an added complication vs no pwa) given the requirement of KIP to talk to the signalk backend. 

Paths are set per the signalk dashboard configuration & not as a standalone webapp (/@mxtommy/kip as opposed to /)

Currently master does not build so this requires https://github.com/mxtommy/Kip/issues/111 to be resolved before final testing and merging (@godind any progress on this?)

Resolves #21

### CODE REVIEW

**Comment by godind** [comment]
Hi James. I've updated a few dependencies, node, angular and more. I need help testing. Could you help. Tommy has been offline a while.

**Comment by godind** [comment]
Its under platform_upgrade. Once tested by someone else I'll merge it onto master. I also have a few AP module fixes.

**Comment by VibroAxe** [comment]
> Hi James. I've updated a few dependencies, node, angular and more. I need help testing to make sure it builds and runs. Could you help? Tommy has been offline a while.

Builds and runs fine for me, works both standalone and deployed into signalk (npm link). I'd definitely support a merge that, this and then version bump and push out?

**Review by godind — APPROVED** [review]
Approved

**Pull request merged**
